apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: py-gitops
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: py-gitops
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: py-gitops
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/debug: "true"
        apps.tanzu.vmware.com/live-update: "true"
        conventions.carto.run/applied-conventions: |-
          developer-conventions/add-source-image-label
          appliveview-sample/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: 792026016066.dkr.ecr.ap-northeast-1.amazonaws.com/115e7280-80e2-11ed-8871-0e1629f28a1d/tap-supply-chain/source-dev1:latest@sha256:18243cd1194864fcf1b9128b97211ac44562d6ef2ac5f3dd9b566df16c819a8f
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: py-gitops
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: py-gitops
    spec:
      containers:
      - image: 792026016066.dkr.ecr.ap-northeast-1.amazonaws.com/115e7280-80e2-11ed-8871-0e1629f28a1d/tap-supply-chain/py-gitops-dev1@sha256:3c289bca1981c029459948958f3206de782e6b81b36696401d277029674f8043
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

